print('두 점 사이의 거리를 계산해주는 프로그램')
x1 = float(input('x1:'))
y1 = float(input('y1:'))
x2 = float(input('x2:'))
y2 = float(input('y2:'))
dis = ((x1 - x2) ** 2 + (y1 - y2) ** 2) ** (0.5)
print('두점 사이의 거리는 %s 입니다' % dis)
